export const REQUEST_POKEMON_DATA = 'REQUEST_POKEMON_DATA';
export const RECEIVE_POKEMON_DATA = 'RECEIVE_POKEMON_DATA';
export const FILTER_POKEMON_DATA = 'FILTER_POKEMON_DATA';
export const REQUEST_SELECTED_POKEMON_DATA = 'REQUEST_SELECTED_POKEMON_DATA';
export const RECEIVE_SELECTED_POKEMON_DATA = 'RECEIVE_SELECTED_POKEMON_DATA';
export const SORT_POKEMON_DATA = 'SORT_POKEMON_DATA';
export const TOGGLE_POKEMON_MODAL = 'TOGGLE_POKEMON_MODAL';
